
export const locales = {
  fi: {
    headerTitle: "Ruoka-analysaattori",
    ariaBackToHome: "Palaa etusivulle",
    ariaChangeLanguage: "Vaihda kieli",
    welcomeTitle: "Tervetuloa Ruoka-analysointiin!",
    welcomeUserTitle: "Tervetuloa takaisin, {name}!",
    welcomeMessage: "Ota kuva ateriastasi, ja kerron sinulle mitä se sisältää, arvion sen ravintoarvoista sekä yksinkertaisen reseptin sen valmistamiseen. Aloita lataamalla kuva yllä.",
    uploaderDragDrop: "Raahaa ja pudota kuva tähän",
    uploaderOr: "tai",
    uploaderClick: "klikkaa valitaksesi tiedosto",
    alertOnlyImages: "Valitse kuvatiedosto.",
    imagePreviewAlt: "Esikatselu",
    buttonAnalyzing: "Analysoidaan...",
    buttonAnalyze: "Analysoi kuva",
    buttonSelectNew: "Valitse uusi",
    errorSelectImage: "Valitse kuva ensin.",
    errorMissingFileInfo: "Kuva tiedostoa ei löytynyt.",
    errorAnalysisFailed: "Analyysi epäonnistui. Varmista, että API-avain on asetettu ja yritä uudelleen.",
    errorTitle: "Virhe!",
    resultTitle: "Analyysin tulos",
    reasonNotFood: "Kuvasta ei tunnistettu ruokaa.",
    ingredientsTitle: "Ainesosat (arvio)",
    nutritionTitle: "Ravitsemustiedot (arvio / annos)",
    nutritionCalories: "Kalorit",
    nutritionProtein: "Proteiini",
    nutritionCarbs: "Hiilihydraatit",
    nutritionFat: "Rasva",
    recipeTitle: "Resepti",
    recipeDifficulty: "Vaikeustaso",
    recipeTime: "Valmistusaika",
    uncertaintyTitle: "Huomioitavaa",
    footerDescription: "Ota kuva ateriastasi ja saat tekoälypohjaisen analyysin sen sisällöstä, ravintoarvoista ja valmistusohjeen.",
    footerLinksTitle: "Linkit",
    footerLinkAbout: "Tietoja sovelluksesta",
    footerLinkTerms: "Käyttöehdot",
    footerLinkPrivacy: "Tietosuojakäytäntö",
    footerFollowTitle: "Seuraa meitä",
    footerDisclaimerTitle: "Vastuuvapauslauseke:",
    footerDisclaimerText: "Tämä sovellus käyttää generatiivista tekoälyä. Tulokset ovat arvioita, eikä niiden tarkkuutta voida taata. Älä tee terveyttä koskevia päätöksiä tämän sovelluksen perusteella. Keskustele aina ravitsemusasiantuntijan kanssa.",
    footerCopyrightText: "© {year} Ruoka-analysaattori. Kaikki oikeudet pidätetään.",
    cookieConsentText: "Käytämme evästeitä parantaaksemme käyttökokemustasi. Jatkamalla sivuston käyttöä hyväksyt evästeiden käytön.",
    cookieAcceptButton: "Hyväksy",
    modalClose: "Sulje",
    aboutTitle: "Tietoja Ruoka-analysaattorista",
    aboutContent1: "Tämä sovellus hyödyntää Googlen Gemini-tekoälymallia analysoidakseen ruokakuvia. Tavoitteenamme on tarjota käyttäjille helppo ja nopea tapa saada arvioita aterioidensa sisällöstä, ravintoarvoista ja jopa reseptejä.",
    aboutContent2: "Sovellus on kehitetty demonstroimaan tekoälyn mahdollisuuksia arkipäivän avustajana. Muista, että kaikki tiedot ovat arvioita ja niitä tulee käyttää suuntaa antavina.",
    termsTitle: "Käyttöehdot",
    termsSection1Title: "Palvelun käyttö",
    termsSection1Content: "Tämän palvelun käyttö on sallittu vain henkilökohtaisiin, ei-kaupallisiin tarkoituksiin. Käyttäjä vastaa kaikesta materiaalista, jonka hän lataa palveluun.",
    termsSection2Title: "Vastuunrajoitus",
    termsSection2Content: "Palveluntarjoaja ei ole vastuussa palvelun tuottamien tietojen tarkkuudesta tai mahdollisista virheistä. Käyttäjä käyttää palvelua omalla vastuullaan.",
    privacyTitle: "Tietosuojakäytäntö",
    privacySection1Title: "Tietojen kerääminen",
    privacySection1Content: "Emme tallenna tai säilytä käyttäjien lataamia kuvia tai niiden analyysituloksia palvelimillemme. Kuvat lähetetään ainoastaan Googlen Gemini API:lle analysoitavaksi ja poistetaan käsittelyn jälkeen.",
    privacySection2Title: "Evästeet",
    privacySection2Content: "Käytämme ainoastaan välttämättömiä evästeitä, kuten evästesuostumuksen tallentamista varten. Emme käytä seuranta- tai markkinointievästeitä.",
    loginGoogle: "Kirjaudu Google-tilillä",
    loginShort: "Kirjaudu",
    logout: "Kirjaudu ulos"
  },
  en: {
    headerTitle: "Food Analyzer",
    ariaBackToHome: "Back to home",
    ariaChangeLanguage: "Change language",
    welcomeTitle: "Welcome to the Food Analyzer!",
    welcomeUserTitle: "Welcome back, {name}!",
    welcomeMessage: "Take a picture of your meal, and I'll tell you what it contains, estimate its nutritional values, and provide a simple recipe to make it. Start by uploading an image above.",
    uploaderDragDrop: "Drag and drop an image here",
    uploaderOr: "or",
    uploaderClick: "click to select a file",
    alertOnlyImages: "Please select an image file.",
    imagePreviewAlt: "Preview",
    buttonAnalyzing: "Analyzing...",
    buttonAnalyze: "Analyze Image",
    buttonSelectNew: "Select New",
    errorSelectImage: "Please select an image first.",
    errorMissingFileInfo: "Image file information not found.",
    errorAnalysisFailed: "Analysis failed. Please ensure your API key is set and try again.",
    errorTitle: "Error!",
    resultTitle: "Analysis Result",
    reasonNotFood: "No food was identified in the image.",
    ingredientsTitle: "Ingredients (estimate)",
    nutritionTitle: "Nutrition Facts (estimate / serving)",
    nutritionCalories: "Calories",
    nutritionProtein: "Protein",
    nutritionCarbs: "Carbohydrates",
    nutritionFat: "Fat",
    recipeTitle: "Recipe",
    recipeDifficulty: "Difficulty",
    recipeTime: "Cook Time",
    uncertaintyTitle: "Please Note",
    footerDescription: "Take a picture of your meal and get an AI-powered analysis of its contents, nutritional values, and a recipe.",
    footerLinksTitle: "Links",
    footerLinkAbout: "About the App",
    footerLinkTerms: "Terms of Service",
    footerLinkPrivacy: "Privacy Policy",
    footerFollowTitle: "Follow Us",
    footerDisclaimerTitle: "Disclaimer:",
    footerDisclaimerText: "This application uses generative AI. The results are estimates and their accuracy cannot be guaranteed. Do not make health-related decisions based on this application. Always consult with a nutrition professional.",
    footerCopyrightText: "© {year} Food Analyzer. All rights reserved.",
    cookieConsentText: "We use cookies to improve your experience. By continuing to use the site, you agree to our use of cookies.",
    cookieAcceptButton: "Accept",
    modalClose: "Close",
    aboutTitle: "About the Food Analyzer",
    aboutContent1: "This application utilizes Google's Gemini AI model to analyze food images. Our goal is to provide users with a quick and easy way to get estimates of their meals' contents, nutritional values, and even recipes.",
    aboutContent2: "The application was developed to demonstrate the potential of AI as an everyday assistant. Remember that all information provided is an estimate and should be used as a guideline only.",
    termsTitle: "Terms of Service",
    termsSection1Title: "Use of Service",
    termsSection1Content: "This service is permitted for personal, non-commercial use only. The user is responsible for all material they upload to the service.",
    termsSection2Title: "Limitation of Liability",
    termsSection2Content: "The service provider is not responsible for the accuracy of the information generated by the service or any potential errors. The user uses the service at their own risk.",
    privacyTitle: "Privacy Policy",
    privacySection1Title: "Data Collection",
    privacySection1Content: "We do not save or store the images uploaded by users or their analysis results on our servers. Images are sent only to the Google Gemini API for analysis and are deleted after processing.",
    privacySection2Title: "Cookies",
    privacySection2Content: "We only use essential cookies, such as for storing cookie consent. We do not use tracking or marketing cookies.",
    loginGoogle: "Sign in with Google",
    loginShort: "Sign in",
    logout: "Sign out"
  },
};

export type Strings = typeof locales.en;
